/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-CommonDataTypes"
 * 	found in "e2ap.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_ProtocolIE_Container_H_
#define	_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RICsubscriptionRequest_IEs;
struct RICsubscriptionResponse_IEs;
struct RICsubscriptionFailure_IEs;
struct RICsubscriptionDeleteRequest_IEs;
struct RICsubscriptionDeleteResponse_IEs;
struct RICsubscriptionDeleteFailure_IEs;
struct RICsubscriptionDeleteRequired_IEs;
struct RICindication_IEs;
struct RICcontrolRequest_IEs;
struct RICcontrolAcknowledge_IEs;
struct RICcontrolFailure_IEs;
struct ErrorIndication_IEs;
struct E2setupRequestIEs;
struct E2setupResponseIEs;
struct E2setupFailureIEs;
struct E2nodeConfigurationUpdate_IEs;
struct E2nodeConfigurationUpdateAcknowledge_IEs;
struct E2nodeConfigurationUpdateFailure_IEs;
struct ResetRequestIEs;
struct ResetResponseIEs;
struct RICserviceQuery_IEs;
struct E2RemovalRequestIEs;
struct E2RemovalResponseIEs;
struct E2RemovalFailureIEs;

/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_185P0 {
	A_SEQUENCE_OF(struct RICsubscriptionRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P0_t;
typedef struct ProtocolIE_Container_185P1 {
	A_SEQUENCE_OF(struct RICsubscriptionResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P1_t;
typedef struct ProtocolIE_Container_185P2 {
	A_SEQUENCE_OF(struct RICsubscriptionFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P2_t;
typedef struct ProtocolIE_Container_185P3 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P3_t;
typedef struct ProtocolIE_Container_185P4 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P4_t;
typedef struct ProtocolIE_Container_185P5 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P5_t;
typedef struct ProtocolIE_Container_185P6 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteRequired_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P6_t;
typedef struct ProtocolIE_Container_185P7 {
	A_SEQUENCE_OF(struct RICindication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P7_t;
typedef struct ProtocolIE_Container_185P8 {
	A_SEQUENCE_OF(struct RICcontrolRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P8_t;
typedef struct ProtocolIE_Container_185P9 {
	A_SEQUENCE_OF(struct RICcontrolAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P9_t;
typedef struct ProtocolIE_Container_185P10 {
	A_SEQUENCE_OF(struct RICcontrolFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P10_t;
typedef struct ProtocolIE_Container_185P11 {
	A_SEQUENCE_OF(struct ErrorIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P11_t;
typedef struct ProtocolIE_Container_185P12 {
	A_SEQUENCE_OF(struct E2setupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P12_t;
typedef struct ProtocolIE_Container_185P13 {
	A_SEQUENCE_OF(struct E2setupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P13_t;
typedef struct ProtocolIE_Container_185P14 {
	A_SEQUENCE_OF(struct E2setupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P14_t;
typedef struct ProtocolIE_Container_185P15 {
	A_SEQUENCE_OF(struct E2nodeConfigurationUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P15_t;
typedef struct ProtocolIE_Container_185P16 {
	A_SEQUENCE_OF(struct E2nodeConfigurationUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P16_t;
typedef struct ProtocolIE_Container_185P17 {
	A_SEQUENCE_OF(struct E2nodeConfigurationUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P17_t;
typedef struct ProtocolIE_Container_185P18 {
	A_SEQUENCE_OF(struct ResetRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P18_t;
typedef struct ProtocolIE_Container_185P19 {
	A_SEQUENCE_OF(struct ResetResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P19_t;
typedef struct ProtocolIE_Container_185P20 {
	A_SEQUENCE_OF(struct RICserviceQuery_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P20_t;
typedef struct ProtocolIE_Container_185P21 {
	A_SEQUENCE_OF(struct E2RemovalRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P21_t;
typedef struct ProtocolIE_Container_185P22 {
	A_SEQUENCE_OF(struct E2RemovalResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P22_t;
typedef struct ProtocolIE_Container_185P23 {
	A_SEQUENCE_OF(struct E2RemovalFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_185P23_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_185P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_185P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_185P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_185P23_constr_47;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Container_H_ */
#include <asn_internal.h>
